version: "3.2"

services:
  instacarro:
    image: 'mongo:latest'
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - instacarro-network 

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: api_instacarro
    environment:
      MONGODB_CONNECTION_URL: mongodb://instacarro:27017/instacarro
      PORT: 3000
      JWT_KEY: 'any_token'
    volumes:
      - ./upload:/app/upload
      - /app/node_modules
      - .:/app
    depends_on:
      - instacarro
    networks:
      - instacarro-network  

networks:
  instacarro-network:
    driver: bridge

volumes:
  mongodb_data_container:
