components:
  schemas:
    AuctionBid:
      type: object
      properties:
        car_id:
          type: string
          example: "65d0df0177435ebd1a29e2b9"
        value:
          type: number
          example: 25000

/auction-bid/list/{id}:
  get:
    summary: "Listar todos os lances de um veiculo"
    description: "Esta rota é usada para listar todos lances oferecidos por um veiculo."
    tags: ["Lances"]
    parameters:
      - name: id
        in: path
        description: "id do carro para filtrar."
        required: true
        schema:
          type: string
    responses:
      "200":
        description: "Operação bem-sucedida."
        content:
          application/json:
            example:
              total: 138
              data:
                - id: "65d0df0177435ebd1a29e2b9"
                  value: "Ford"
                  user_id: "Focus"
                  car_id: 2020
                  date: 1708187393275
                  user:
                    name: "Gian"
                    email: "gian_sss@live.com"

                - id: "65d0df0177435ebd1a29e255"
                  value: "Ford"
                  user_id: "Focus"
                  car_id: 2020
                  date: 1708187393275
                  user:
                    name: "Gian"
                    email: "gian_ss@live.com"
/auction-bid:
  post:
    summary: "Cadastro de lances"
    description: "Esta rota é usada para cadastrar um novo lance."
    tags: ["Lances"]
    security: [{ ApiKeyAuth: [] }]
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuctionBid"
    responses:
      "200":
        description: "Operação bem-sucedida."
        content:
          application/json:
            example:
              data:
                id: "65d0df0177435ebd1a29e255"
                value: "Ford"
                car_id: 2020
      "400":
        description: "Parâmetros inválidos."
      "401":
        description: "Sem autorização."
      "403":
        description: "Acesso bloqueado."
